--; sistema gestion bancaria
--CREATE DATABASE Grune_Bank
USE [Grune_Bank]
GO


IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AirTime]'))
BEGIN
	ALTER TABLE [dbo].[AirTime] DROP CONSTRAINT IF EXISTS [FK_AirTime_Users]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AirTime]'))
BEGIN
	ALTER TABLE [dbo].[AirTime] DROP CONSTRAINT IF EXISTS [FK_AirTime_Operators]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Transactions]'))
BEGIN
	ALTER TABLE [dbo].[Transactions] DROP CONSTRAINT IF EXISTS [FK_Transactions_Users]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[ServicePayments]'))
BEGIN
	ALTER TABLE [dbo].[ServicePayments] DROP CONSTRAINT IF EXISTS [FK_ServicePayments_Services]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[ServicePayments]'))
BEGIN
	ALTER TABLE [dbo].[ServicePayments] DROP CONSTRAINT IF EXISTS [FK_ServicePayments_Users]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Cards]'))
BEGIN
	ALTER TABLE [dbo].[Cards] DROP CONSTRAINT IF EXISTS [FK_Cards_Users]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Accounts]'))
BEGIN
	ALTER TABLE [dbo].[Accounts] DROP CONSTRAINT IF EXISTS [FK_Accounts_AccountTypes]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Accounts]'))
BEGIN
	ALTER TABLE [dbo].[Accounts] DROP CONSTRAINT IF EXISTS [FK_Accounts_Users]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Transfers]'))
BEGIN
	ALTER TABLE [dbo].[Transfers] DROP CONSTRAINT IF EXISTS [FK_Transfers_SourceAccounts]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Transfers]'))
BEGIN
	ALTER TABLE [dbo].[Transfers] DROP CONSTRAINT IF EXISTS [FK_Transfers_DestinationAccounts]
END


IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AccountTypes]'))
BEGIN
	DROP TABLE [dbo].[AccountTypes]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Cards]'))
BEGIN
	DROP TABLE [dbo].[Cards]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Transfers]'))
BEGIN
	DROP TABLE [dbo].[Transfers]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Services]'))
BEGIN
	DROP TABLE [dbo].[Services]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[ServicePayments]'))
BEGIN
	DROP TABLE [dbo].[ServicePayments]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Operators]'))
BEGIN
	DROP TABLE [dbo].[Operators]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Transactions]'))
BEGIN
	DROP TABLE [dbo].[Transactions]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AirTime]'))
BEGIN
	DROP TABLE [dbo].[AirTime]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Users]'))
BEGIN
	DROP TABLE [dbo].[Users]
END
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Accounts]'))
BEGIN
	DROP TABLE [dbo].[Accounts]
END



IF OBJECT_ID('Users') IS NULL
BEGIN
	CREATE TABLE Users
	(
		UserId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
		FirstName NVARCHAR(20) NOT NULL,
		LastName NVARCHAR(20) NOT NULL,
		Email NVARCHAR(50) NOT NULL,
		Phone NVARCHAR(20) NOT NULL,
		Address NVARCHAR(100) NOT NULL,
		RegistrationDate DATETIME NOT NULL,
		Balance MONEY NOT NULL
	);
END

IF OBJECT_ID('AccountTypes') IS NULL
BEGIN
CREATE TABLE AccountTypes --; DEBITO, CREDITO, AHORRO
(
	AccountTypeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	TypeName NVARCHAR(20) NOT NULL
);
END

IF OBJECT_ID('Accounts') IS NULL
BEGIN
	CREATE TABLE Accounts
	(
		AccountId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
		UserId INT NOT NULL,
		AccountTypeId INT NOT NULL,
		AccountNumber NVARCHAR(50) NOT NULL,
		Balance MONEY NOT NULL,
		OpeningDate DATETIME NOT NULL
	);
		ALTER TABLE Accounts
			WITH CHECK ADD CONSTRAINT [FK_Accounts_AccountTypes]
			FOREIGN KEY([AccountTypeId]) REFERENCES AccountTypes([AccountTypeId])
		ALTER TABLE Accounts
			WITH CHECK ADD CONSTRAINT [FK_Accounts_Users]
			FOREIGN KEY([UserId]) REFERENCES Users([UserId])
END

IF OBJECT_ID('Cards') IS NULL
BEGIN
	CREATE TABLE Cards
	(
		CardId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
		UserId INT NOT NULL,
		CardNumber NVARCHAR(16) NOT NULL,
		ExpirationDate DATETIME NOT NULL,
		Cvv INT NOT NULL,
		Active BIT DEFAULT 0
	);
		ALTER TABLE [Cards]
			WITH CHECK ADD CONSTRAINT [FK_Cards_Users]
			FOREIGN KEY([UserId]) REFERENCES Users([UserId])
END

IF OBJECT_ID('Transfers') IS NULL
BEGIN
	CREATE TABLE Transfers
	(
		TransferId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,	
		SourceAccountId INT NOT NULL,			
		DestinationAccountId INT NOT NULL,		
		Amount MONEY NOT NULL,					
		TransferDate DATETIME NOT NULL,
		TransferType NVARCHAR(20) NOT NULL,		
		TransferStatus NVARCHAR(20) NOT NULL	--; pending, complete, failed
	);
	ALTER TABLE Transfers
		WITH CHECK ADD CONSTRAINT [FK_Transfers_SourceAccounts]
		FOREIGN KEY([SourceAccountId]) REFERENCES Accounts([AccountId])
	ALTER TABLE Transfers
		WITH CHECK ADD CONSTRAINT [FK_Transfers_DestinationAccounts]
		FOREIGN KEY([DestinationAccountId]) REFERENCES Accounts([AccountId])
END

IF OBJECT_ID('Services') IS NULL
BEGIN
	CREATE TABLE Services
	(
		ServiceId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
		Name NVARCHAR(20) NOT NULL,				
		Provider NVARCHAR(20)					
	);
END

IF OBJECT_ID('ServicePaymets') IS NULL
BEGIN
	CREATE TABLE ServicePayments
	(
		ServicePaymentId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
		ServiceId INT NOT NULL,
		UserId INT NOT NULL,
		Amount MONEY NOT NULL,
		PaymentDate DATETIME NOT NULL,
		Barcode NVARCHAR(255) NOT NULL			
	);
	ALTER TABLE ServicePayments
		WITH CHECK ADD CONSTRAINT [FK_ServicePayments_Services]
		FOREIGN KEY([ServiceId]) REFERENCES Services([ServiceId])
	ALTER TABLE ServicePayments
		WITH CHECK ADD CONSTRAINT [FK_ServciePayments_Users]
		FOREIGN KEY([UserId]) REFERENCES Users([UserId])
END


IF OBJECT_ID('Operators') IS NULL
BEGIN
	CREATE TABLE Operators
	(
		OperatorId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,	
		Name NVARCHAR(20) NOT NULL				--; telcel, movistar, at&t
	);
END


IF OBJECT_ID('Transactions') IS NULL
BEGIN
	CREATE TABLE Transactions
	(
		TransactionId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
		UserId INT NOT NULL,
		TransactionType NVARCHAR(20),
		Amount MONEY,
		TransactionDate DATETIME NOT NULL,
		Description NVARCHAR(255)
	);
	ALTER TABLE Transactions
		WITH CHECK ADD CONSTRAINT [FK_Transactions_Users]
		FOREIGN KEY([UserId]) REFERENCES Users([UserId])
END

IF OBJECT_ID('AirTime') IS NULL
BEGIN
	CREATE TABLE AirTime
	(
		AirTimeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
		UserId INT NOT NULL,
		OperatorId INT NOT NULL,
		Amount MONEY NOT NULL,
		AirTimeDate DATETIME NOT NULL
	);
	ALTER TABLE AirTime
		WITH CHECK ADD CONSTRAINT [FK_AirTime_Users]
		FOREIGN KEY([UserId]) REFERENCES Users([UserId])
	ALTER TABLE AirTime
		WITH CHECK ADD CONSTRAINT [FK_AirTime_Operators]
		FOREIGN KEY([OperatorId]) REFERENCES Operators([OperatorId])
END